In [18]:
#Numpy
#np=numerical python

In [19]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [20]:
import numpy as np

In [21]:
#Creating Arrays

In [22]:
sample_array=np.array([1,2,3,4])

In [23]:
sample_array

array([1, 2, 3, 4])

In [24]:
#2D Array(a Matrix) with 2 rows and 2 columns

In [25]:
sample_array_2=np.array([[1,2],[3,4]])

In [26]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [27]:
s1=np.array([[4,6],[7,8]])

In [28]:
s1

array([[4, 6],
       [7, 8]])

In [29]:
#3D tensor (2 matrices,each with 2 rows and 2 columns)

In [35]:
tensor_3= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [36]:
tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
tensor_4= np.array([[[11,12],[13,14]],[[15,16],[17,18]]])

In [38]:
tensor_4

array([[[11, 12],
        [13, 14]],

       [[15, 16],
        [17, 18]]])

In [39]:
# Dimension

In [40]:
# if the array 0-D Array(Scalar)= eg. 5
#if the array is 1-D array(Vector) = eg. [1,2,3,4]
# if the array is 2-D Array(Matrix Manipluation)(rows and columns)
#if the array is 3-D Array (Tensor)(page,row,column)

In [41]:
# Arrays Properties

In [43]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [44]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# Shape[ First parameter is rows and another one is column]

In [49]:
sample_array.shape

(2, 3)

In [50]:
#dimensions

In [51]:
sample_array.ndim

2

In [52]:
#total elements

In [53]:
sample_array.size

6

In [54]:
#Data Type

In [58]:
sample_array.dtype

dtype('int64')

In [57]:
tensor4= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [59]:
tensor4.shape

(2, 2, 2)

In [60]:
tensor4.size

8

In [61]:
tensor4.dtype

dtype('int64')

In [62]:
tensor4.ndim

3

In [63]:
#Special Arrays

In [64]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
np.ones((140,140))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(140, 140))

In [71]:
np.arange(0,10,2)# parameter passed are start,stop,step

array([0, 2, 4, 6, 8])

In [72]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [77]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [79]:
np.linspace(0,1,10) # 3 parameter is of no of value

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [80]:
#Indexing and Slicing

In [81]:
sample_array=np.array([10,20,30,40,50])

In [82]:
sample_array

array([10, 20, 30, 40, 50])

In [83]:
sample_array[0]

np.int64(10)

In [84]:
sample_array[2]

np.int64(30)

In [85]:
sample_array[-1]

np.int64(50)

In [86]:
#Slicing

In [88]:
sample_array[1:3] # we need to give colons one side is start and other one is stop

array([20, 30])

In [89]:
sample_array[1:-1]

array([20, 30, 40])

# Array Operations

In [90]:
a=np.array([1,2,3])

In [92]:
b=np.array([4,5,6])

In [93]:
a

array([1, 2, 3])

In [94]:
b

array([4, 5, 6])

In [95]:
a+b

array([5, 7, 9])

In [96]:
a-b

array([-3, -3, -3])

In [97]:
a*b

array([ 4, 10, 18])

In [98]:
a/b

array([0.25, 0.4 , 0.5 ])

In [99]:
c=np.array([11,12,13])
d=np.array([4,5,6])

In [100]:
c

array([11, 12, 13])

In [101]:
d

array([4, 5, 6])

In [102]:
c+d

array([15, 17, 19])

In [104]:
c-d

array([7, 7, 7])

In [105]:
c*d

array([44, 60, 78])

In [106]:
c/d

array([2.75      , 2.4       , 2.16666667])

In [107]:
# Mathematical Function

In [109]:
sample_array=np.array([1,4,9])

In [110]:
sample_array

array([1, 4, 9])

In [111]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [112]:
sample_array=np.array([10,44,6])

In [113]:
sample_array

array([10, 44,  6])

In [114]:
np.sqrt(sample_array)

array([3.16227766, 6.63324958, 2.44948974])

In [116]:
sample_array=np.array([1,4,9])

In [117]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [118]:
sample_array=np.array([10,44,6])

In [119]:
np.exp(sample_array)

array([2.20264658e+04, 1.28516001e+19, 4.03428793e+02])

In [121]:
sample_array=np.array([1,4,9])
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [120]:
np.log(sample_array)

array([2.30258509, 3.78418963, 1.79175947])

In [122]:
# Statistical Function

In [123]:
sample_array=np.array([1,2,3,4,5])

In [124]:
sample_array

array([1, 2, 3, 4, 5])

In [125]:
np.mean(sample_array)

np.float64(3.0)

In [127]:
np.median(sample_array)

np.float64(3.0)

In [131]:
np.std(sample_array)# Standard Deviation

np.float64(1.4142135623730951)

In [132]:
np.min(sample_array)

np.int64(1)

In [133]:
np.max(sample_array)

np.int64(5)

In [137]:
# Reshaping Arrays => changing dimension of array


In [144]:
sample_array=np.arange(0,6)

In [145]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [147]:
reshaped=sample_array.reshape(2,3)

In [148]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [149]:
# Flattening

In [153]:
sample_array=np.array([[1,2],[4,5]])

In [154]:
sample_array

array([[1, 2],
       [4, 5]])

In [156]:
sample_array.flatten()

array([1, 2, 4, 5])

In [157]:
sample_array=np.array([[1,2,3],[4,5,6]])

In [158]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
sample_array.flatten()

array([1, 2, 3, 4, 5, 6])

In [160]:
tensor4= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [161]:
tensor4

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [162]:
tensor4.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [163]:
# Joining  Arrays

In [164]:
s=np.array([1,2,3,4,5])
s1=np.array([6,7,8,9,10])

In [166]:
s


array([1, 2, 3, 4, 5])

In [168]:
np.concatenate((s,s1))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
# Splitting Arrays

In [175]:
sample_array = np.array([1,2,3,4])

In [177]:
sample_array


array([1, 2, 3, 4])

In [180]:
np.array_split(sample_array,2)# 1 parameter is our array and another is no of parts which we want

[array([1, 2]), array([3, 4])]

In [182]:
# Random Module


In [183]:
np.random.rand(3)

array([0.18978337, 0.49697544, 0.00210742])

In [186]:
np.random.randint(1,10,5)

array([2, 7, 2, 7, 6], dtype=int32)